### ISSUE TITLE
404: NOT_FOUND Code: NOT_FOUND

### ISSUE THREAD

**Issue by onhate** [Wakeful-Cloud/bulma-on-demand#32]
![2022-11-03T08-37-00](https://user-images.githubusercontent.com/980905/199711067-ad798cff-7db1-4c5f-bed0-08cb1485cae9.png)

**Comment by Wakeful-Cloud** [comment]
I've fixed some issues with SvelteKit routing that may have caused this, but I'm having other difficulties with deploying new versions to Vercel. If you need this working ASAP, you should be able to run the Docker container without any issues.

[Edit]
Still working on this with Vercel support. No ETA as of now.

**Comment by Wakeful-Cloud** [comment]
Fixed in [2dc82a6](https://github.com/Wakeful-Cloud/bulma-on-demand/commit/2dc82a617de15c72cf615f85464246b84c0459ec)
